inputs:
  name:
    description: 'Name'
    required: true
  android-version:
    description: 'flutter version'
    required: true
    

name: "Version actions"
description: "Checks out the repository and does something"
runs:
  using: "composite"
  steps: 
  - run: |
      echo ${{ inputs.name }}
    shell: bash

  - run: |
      echo ${{ inputs.android-version }}
    shell: bash
